import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// default metadata name 
export const metadata = {
  title: "My Users & Blogs App", 
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >

      {/* project er shob kisu ekhane dekhabe  */}
      <body className="min-h-full flex flex-col">
        
        <Navbar />
        {children}
        </body>
    </html>
  );
}
